-- Countries 테이블 데이터 삽입
INSERT INTO `jdosa_countries` (`country_code`, `country_name`) VALUES
('US', 'United States'),
('KR', 'South Korea'),
('JP', 'Japan'),
('CN', 'China'),
('TW', 'Taiwan'),
('GB', 'United Kingdom'),
('DE', 'Germany'),
('FR', 'France'),
('IT', 'Italy'),
('ES', 'Spain'),
('CA', 'Canada'),
('AU', 'Australia'),
('BR', 'Brazil'),
('IN', 'India'),
('RU', 'Russia'),
('MX', 'Mexico'),
('NL', 'Netherlands'),
('BE', 'Belgium'),
('CH', 'Switzerland'),
('AT', 'Austria'),
('SE', 'Sweden'),
('NO', 'Norway'),
('DK', 'Denmark'),
('FI', 'Finland'),
('PL', 'Poland'),
('CZ', 'Czech Republic'),
('HU', 'Hungary'),
('PT', 'Portugal'),
('GR', 'Greece'),
('TR', 'Turkey'),
('IL', 'Israel'),
('SA', 'Saudi Arabia'),
('AE', 'United Arab Emirates'),
('SG', 'Singapore'),
('MY', 'Malaysia'),
('TH', 'Thailand'),
('VN', 'Vietnam'),
('PH', 'Philippines'),
('ID', 'Indonesia'),
('NZ', 'New Zealand'),
('ZA', 'South Africa'),
('EG', 'Egypt'),
('NG', 'Nigeria'),
('AR', 'Argentina'),
('CL', 'Chile'),
('CO', 'Colombia'),
('PE', 'Peru'),
('VE', 'Venezuela'),
('UY', 'Uruguay'),
('EC', 'Ecuador'),
('BO', 'Bolivia'),
('PY', 'Paraguay'),
('IE', 'Ireland'),
('LU', 'Luxembourg'),
('MT', 'Malta'),
('CY', 'Cyprus'),
('IS', 'Iceland'),
('LI', 'Liechtenstein'),
('MC', 'Monaco'),
('SM', 'San Marino'),
('VA', 'Vatican City'),
('AD', 'Andorra'),
('HR', 'Croatia'),
('SI', 'Slovenia'),
('SK', 'Slovakia'),
('EE', 'Estonia'),
('LV', 'Latvia'),
('LT', 'Lithuania'),
('BG', 'Bulgaria'),
('RO', 'Romania'),
('RS', 'Serbia'),
('BA', 'Bosnia and Herzegovina'),
('ME', 'Montenegro'),
('MK', 'North Macedonia'),
('AL', 'Albania'),
('XK', 'Kosovo'),
('MD', 'Moldova'),
('UA', 'Ukraine'),
('BY', 'Belarus'),
('GE', 'Georgia'),
('AM', 'Armenia'),
('AZ', 'Azerbaijan'),
('KZ', 'Kazakhstan'),
('UZ', 'Uzbekistan'),
('TM', 'Turkmenistan'),
('KG', 'Kyrgyzstan'),
('TJ', 'Tajikistan'),
('AF', 'Afghanistan'),
('PK', 'Pakistan'),
('BD', 'Bangladesh'),
('LK', 'Sri Lanka'),
('MV', 'Maldives'),
('BT', 'Bhutan'),
('NP', 'Nepal'),
('MM', 'Myanmar'),
('KH', 'Cambodia'),
('LA', 'Laos'),
('BN', 'Brunei'),
('MN', 'Mongolia'),
('KP', 'North Korea'),
('MO', 'Macau'),
('HK', 'Hong Kong'),
('FJ', 'Fiji'),
('PG', 'Papua New Guinea'),
('SB', 'Solomon Islands'),
('NC', 'New Caledonia'),
('VU', 'Vanuatu'),
('WS', 'Samoa'),
('TO', 'Tonga'),
('CK', 'Cook Islands'),
('PF', 'French Polynesia'),
('GU', 'Guam'),
('FM', 'Micronesia'),
('PW', 'Palau'),
('MH', 'Marshall Islands'),
('KI', 'Kiribati'),
('NR', 'Nauru'),
('TV', 'Tuvalu'),
('DZ', 'Algeria'),
('MA', 'Morocco'),
('TN', 'Tunisia'),
('LY', 'Libya'),
('SD', 'Sudan'),
('SS', 'South Sudan'),
('ET', 'Ethiopia'),
('ER', 'Eritrea'),
('DJ', 'Djibouti'),
('SO', 'Somalia'),
('KE', 'Kenya'),
('UG', 'Uganda'),
('TZ', 'Tanzania'),
('RW', 'Rwanda'),
('BI', 'Burundi'),
('CD', 'Democratic Republic of the Congo'),
('CG', 'Republic of the Congo'),
('CF', 'Central African Republic'),
('TD', 'Chad'),
('CM', 'Cameroon'),
('GQ', 'Equatorial Guinea'),
('GA', 'Gabon'),
('ST', 'São Tomé and Príncipe'),
('GH', 'Ghana'),
('TG', 'Togo'),
('BJ', 'Benin'),
('NE', 'Niger'),
('BF', 'Burkina Faso'),
('ML', 'Mali'),
('SN', 'Senegal'),
('GM', 'Gambia'),
('GW', 'Guinea-Bissau'),
('GN', 'Guinea'),
('SL', 'Sierra Leone'),
('LR', 'Liberia'),
('CI', 'Côte d\'Ivoire'),
('MR', 'Mauritania'),
('MZ', 'Mozambique'),
('ZW', 'Zimbabwe'),
('ZM', 'Zambia'),
('MW', 'Malawi'),
('MG', 'Madagascar'),
('MU', 'Mauritius'),
('SC', 'Seychelles'),
('KM', 'Comoros'),
('RE', 'Réunion'),
('YT', 'Mayotte'),
('BW', 'Botswana'),
('NA', 'Namibia'),
('SZ', 'Eswatini'),
('LS', 'Lesotho'),
('AO', 'Angola'),
('CV', 'Cape Verde'),
('SH', 'Saint Helena');

-- States 테이블 데이터 삽입 (미국 주)
INSERT INTO `jdosa_states` (`state_code`, `state_name`, `country_code`) VALUES
('AL', 'Alabama', 'US'),
('AK', 'Alaska', 'US'),
('AZ', 'Arizona', 'US'),
('AR', 'Arkansas', 'US'),
('CA', 'California', 'US'),
('CO', 'Colorado', 'US'),
('CT', 'Connecticut', 'US'),
('DE', 'Delaware', 'US'),
('FL', 'Florida', 'US'),
('GA', 'Georgia', 'US'),
('HI', 'Hawaii', 'US'),
('ID', 'Idaho', 'US'),
('IL', 'Illinois', 'US'),
('IN', 'Indiana', 'US'),
('IA', 'Iowa', 'US'),
('KS', 'Kansas', 'US'),
('KY', 'Kentucky', 'US'),
('LA', 'Louisiana', 'US'),
('ME', 'Maine', 'US'),
('MD', 'Maryland', 'US'),
('MA', 'Massachusetts', 'US'),
('MI', 'Michigan', 'US'),
('MN', 'Minnesota', 'US'),
('MS', 'Mississippi', 'US'),
('MO', 'Missouri', 'US'),
('MT', 'Montana', 'US'),
('NE', 'Nebraska', 'US'),
('NV', 'Nevada', 'US'),
('NH', 'New Hampshire', 'US'),
('NJ', 'New Jersey', 'US'),
('NM', 'New Mexico', 'US'),
('NY', 'New York', 'US'),
('NC', 'North Carolina', 'US'),
('ND', 'North Dakota', 'US'),
('OH', 'Ohio', 'US'),
('OK', 'Oklahoma', 'US'),
('OR', 'Oregon', 'US'),
('PA', 'Pennsylvania', 'US'),
('RI', 'Rhode Island', 'US'),
('SC', 'South Carolina', 'US'),
('SD', 'South Dakota', 'US'),
('TN', 'Tennessee', 'US'),
('TX', 'Texas', 'US'),
('UT', 'Utah', 'US'),
('VT', 'Vermont', 'US'),
('VA', 'Virginia', 'US'),
('WA', 'Washington', 'US'),
('WV', 'West Virginia', 'US'),
('WI', 'Wisconsin', 'US'),
('WY', 'Wyoming', 'US'),
('DC', 'District of Columbia', 'US'),
('AS', 'American Samoa', 'US'),
('GU', 'Guam', 'US'),
('MP', 'Northern Mariana Islands', 'US'),
('PR', 'Puerto Rico', 'US'),
('VI', 'U.S. Virgin Islands', 'US');

-- 데이터 확인 쿼리
SELECT COUNT(*) as country_count FROM `jdosa_countries`;
SELECT COUNT(*) as state_count FROM `jdosa_states`;

-- 특정 국가 검색 예시
SELECT * FROM `jdosa_countries` WHERE `country_code` IN ('US', 'KR', 'JP', 'CN', 'GB');

-- 미국 주 검색 예시
SELECT * FROM `jdosa_states` WHERE `country_code` = 'US' ORDER BY `state_name`;