<?php

use yii\db\Migration;

/**
 * Handles the creation of table `{{%countries}}`.
 */
class m250714_120000_create_countries_table extends Migration
{
    /**
     * {@inheritdoc}
     */
    public function safeUp()
    {
        $this->createTable('{{%countries}}', [
            'id' => $this->primaryKey(),
            'country_code' => $this->string(2)->notNull()->unique()->comment('ISO 3166-1 alpha-2 country code'),
            'country_name' => $this->string(100)->notNull()->comment('Full country name'),
            'created_at' => $this->timestamp()->defaultExpression('CURRENT_TIMESTAMP'),
            'updated_at' => $this->timestamp()->defaultExpression('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
        ]);

        // Add index for better performance
        $this->createIndex('idx-countries-country_code', '{{%countries}}', 'country_code');
        
        // Insert common countries data
        $this->batchInsert('{{%countries}}', ['country_code', 'country_name'], [
            ['US', 'United States'],
            ['KR', 'South Korea'],
            ['JP', 'Japan'],
            ['CN', 'China'],
            ['TW', 'Taiwan'],
            ['GB', 'United Kingdom'],
            ['DE', 'Germany'],
            ['FR', 'France'],
            ['IT', 'Italy'],
            ['ES', 'Spain'],
            ['CA', 'Canada'],
            ['AU', 'Australia'],
            ['BR', 'Brazil'],
            ['IN', 'India'],
            ['RU', 'Russia'],
            ['MX', 'Mexico'],
            ['NL', 'Netherlands'],
            ['BE', 'Belgium'],
            ['CH', 'Switzerland'],
            ['AT', 'Austria'],
            ['SE', 'Sweden'],
            ['NO', 'Norway'],
            ['DK', 'Denmark'],
            ['FI', 'Finland'],
            ['PL', 'Poland'],
            ['CZ', 'Czech Republic'],
            ['HU', 'Hungary'],
            ['PT', 'Portugal'],
            ['GR', 'Greece'],
            ['TR', 'Turkey'],
            ['IL', 'Israel'],
            ['SA', 'Saudi Arabia'],
            ['AE', 'United Arab Emirates'],
            ['SG', 'Singapore'],
            ['MY', 'Malaysia'],
            ['TH', 'Thailand'],
            ['VN', 'Vietnam'],
            ['PH', 'Philippines'],
            ['ID', 'Indonesia'],
            ['NZ', 'New Zealand'],
            ['ZA', 'South Africa'],
            ['EG', 'Egypt'],
            ['NG', 'Nigeria'],
            ['AR', 'Argentina'],
            ['CL', 'Chile'],
            ['CO', 'Colombia'],
            ['PE', 'Peru'],
            ['VE', 'Venezuela'],
            ['UY', 'Uruguay'],
            ['EC', 'Ecuador'],
            ['BO', 'Bolivia'],
            ['PY', 'Paraguay'],
            ['IE', 'Ireland'],
            ['LU', 'Luxembourg'],
            ['MT', 'Malta'],
            ['CY', 'Cyprus'],
            ['IS', 'Iceland'],
            ['LI', 'Liechtenstein'],
            ['MC', 'Monaco'],
            ['SM', 'San Marino'],
            ['VA', 'Vatican City'],
            ['AD', 'Andorra'],
            ['HR', 'Croatia'],
            ['SI', 'Slovenia'],
            ['SK', 'Slovakia'],
            ['EE', 'Estonia'],
            ['LV', 'Latvia'],
            ['LT', 'Lithuania'],
            ['BG', 'Bulgaria'],
            ['RO', 'Romania'],
            ['RS', 'Serbia'],
            ['BA', 'Bosnia and Herzegovina'],
            ['ME', 'Montenegro'],
            ['MK', 'North Macedonia'],
            ['AL', 'Albania'],
            ['XK', 'Kosovo'],
            ['MD', 'Moldova'],
            ['UA', 'Ukraine'],
            ['BY', 'Belarus'],
            ['GE', 'Georgia'],
            ['AM', 'Armenia'],
            ['AZ', 'Azerbaijan'],
            ['KZ', 'Kazakhstan'],
            ['UZ', 'Uzbekistan'],
            ['TM', 'Turkmenistan'],
            ['KG', 'Kyrgyzstan'],
            ['TJ', 'Tajikistan'],
            ['AF', 'Afghanistan'],
            ['PK', 'Pakistan'],
            ['BD', 'Bangladesh'],
            ['LK', 'Sri Lanka'],
            ['MV', 'Maldives'],
            ['BT', 'Bhutan'],
            ['NP', 'Nepal'],
            ['MM', 'Myanmar'],
            ['KH', 'Cambodia'],
            ['LA', 'Laos'],
            ['BN', 'Brunei'],
            ['MN', 'Mongolia'],
            ['KP', 'North Korea'],
            ['MO', 'Macau'],
            ['HK', 'Hong Kong'],
            ['FJ', 'Fiji'],
            ['PG', 'Papua New Guinea'],
            ['SB', 'Solomon Islands'],
            ['NC', 'New Caledonia'],
            ['VU', 'Vanuatu'],
            ['WS', 'Samoa'],
            ['TO', 'Tonga'],
            ['CK', 'Cook Islands'],
            ['PF', 'French Polynesia'],
            ['GU', 'Guam'],
            ['FM', 'Micronesia'],
            ['PW', 'Palau'],
            ['MH', 'Marshall Islands'],
            ['KI', 'Kiribati'],
            ['NR', 'Nauru'],
            ['TV', 'Tuvalu'],
            ['DZ', 'Algeria'],
            ['MA', 'Morocco'],
            ['TN', 'Tunisia'],
            ['LY', 'Libya'],
            ['SD', 'Sudan'],
            ['SS', 'South Sudan'],
            ['ET', 'Ethiopia'],
            ['ER', 'Eritrea'],
            ['DJ', 'Djibouti'],
            ['SO', 'Somalia'],
            ['KE', 'Kenya'],
            ['UG', 'Uganda'],
            ['TZ', 'Tanzania'],
            ['RW', 'Rwanda'],
            ['BI', 'Burundi'],
            ['CD', 'Democratic Republic of the Congo'],
            ['CG', 'Republic of the Congo'],
            ['CF', 'Central African Republic'],
            ['TD', 'Chad'],
            ['CM', 'Cameroon'],
            ['GQ', 'Equatorial Guinea'],
            ['GA', 'Gabon'],
            ['ST', 'São Tomé and Príncipe'],
            ['GH', 'Ghana'],
            ['TG', 'Togo'],
            ['BJ', 'Benin'],
            ['NE', 'Niger'],
            ['BF', 'Burkina Faso'],
            ['ML', 'Mali'],
            ['SN', 'Senegal'],
            ['GM', 'Gambia'],
            ['GW', 'Guinea-Bissau'],
            ['GN', 'Guinea'],
            ['SL', 'Sierra Leone'],
            ['LR', 'Liberia'],
            ['CI', 'Côte d\'Ivoire'],
            ['MR', 'Mauritania'],
            ['MZ', 'Mozambique'],
            ['ZW', 'Zimbabwe'],
            ['ZM', 'Zambia'],
            ['MW', 'Malawi'],
            ['MG', 'Madagascar'],
            ['MU', 'Mauritius'],
            ['SC', 'Seychelles'],
            ['KM', 'Comoros'],
            ['RE', 'Réunion'],
            ['YT', 'Mayotte'],
            ['BW', 'Botswana'],
            ['NA', 'Namibia'],
            ['SZ', 'Eswatini'],
            ['LS', 'Lesotho'],
            ['AO', 'Angola'],
            ['CV', 'Cape Verde'],
            ['SH', 'Saint Helena'],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function safeDown()
    {
        $this->dropTable('{{%countries}}');
    }
}